### ISSUE TITLE
[ASU]First Attack

### ISSUE THREAD

**Issue by hanoul1124** [AkanshDivker/polyengine#4]
```
# Issue : Starting a process with a shell, possible injection detected
# Location : polyengine/polyengine/util/compile.py:21,
             polyengine/polyengine/util/compile.py:26
```
This type of subprocess invocation have some vulnerabilities to Shell injection attacks

**Comment by Ramanu-kds** [comment]
Thank you for our secure issue. We already recognize this problem. But miss code update.

So we improve our code and thank you for your attention. :)

**Comment by Ramanu-kds** [comment]
### **Patch Report**

- Commit ID : 146c9f8

- Cause of vulnerability : There is no check output file name. So that can be inserted Shell code, Special characters. 

- Explanation : I push output file name checking function. That only permits alphabet[a-zA-Z] and space, '_', '+'. The others will be removed.

**Comment by AkanshDivker** [comment]
### **Patch Report**

- Commit ID: 146c9f8 + 229a810

- Cause of vulnerability: Unsafe process invocation method (os.system)

- Explanation: In addition to checking all the input submitted for possible malicious content, replaced the call with subprocess.call which is a safer alternative.
